site_name: peanuts
site_url: https://peanuts.externref.tech

theme:
  name: material
  logo: assets/peanut.png
  favicon: assets/peanut.png
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

plugins:
  - social:
      cards_color:
        fill: "#bf9674" 
        text: "#131314"

nav:
  - 'Welcome!': 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'commands.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list